@extends('fe.master')
@section('navbar')
    @include('fe.navbar')    
@endsection
@section('contact')
    @include('fe.contact')
@endsection
@section('footer')
    @include('fe.footer')    
@endsection