@extends('fe.master')
@section('navbar')
    @include('fe.navbar')
@endsection
@section('shop-detail')
    @include('fe.shop-detail')
@endsection
@section('footer')
    @include('fe.footer')    
@endsection